from pydantic import BaseModel, Field, AliasPath


class SkorozvonAdd(BaseModel):
    type: str = Field(validation_alias=AliasPath("type"), default="")

    lead_id: int = Field(validation_alias=AliasPath("lead", "id"), default="") 
    lead_name: str | None = Field(validation_alias=AliasPath("lead", "name"), default="") 
    lead_comment: str | None = Field(validation_alias=AliasPath("lead", "comment"), default="") 
    lead_post: str | None = Field(validation_alias=AliasPath("lead", "post"), default="") 
    lead_city: str = Field(validation_alias=AliasPath("lead", "city"), default="") 
    lead_business: str  | None = Field(validation_alias=AliasPath("lead", "business"), default="") 
    lead_homepage: str | None = Field(validation_alias=AliasPath("lead", "homepage"), default="") 
    lead_emails: str = Field(validation_alias=AliasPath("lead", "emails", "0"), default="")  
    lead_inn: str | None = Field(validation_alias=AliasPath("lead", "inn"), default="") 
    lead_kpp: str | None = Field(validation_alias=AliasPath("lead", "kpp"), default="") 
    lead_created_at: str = Field(validation_alias=AliasPath("lead", "created_at"), default="") 
    lead_updated_at: str = Field(validation_alias=AliasPath("lead", "updated_at"), default="") 
    lead_deleted_at: str | None = Field(validation_alias=AliasPath("lead", "deleted_at"), default="") 
    lead_parent_lead_id: str | None = Field(validation_alias=AliasPath("lead", "parent_lead_id"), default="") 
    lead_tags: list[str] = Field(validation_alias=AliasPath("lead", "tags"), default="") 
    lead_phones: str = Field(validation_alias=AliasPath("lead", "phones"), default="") 

    contact_id: str = Field(validation_alias=AliasPath("contact", "id"), default="")
    contact_name: str = Field(validation_alias=AliasPath("contact", "name"), default="")
    contact_comment: str = Field(validation_alias=AliasPath("contact", "comment"), default="")
    contact_post: str = Field(validation_alias=AliasPath("contact", "post"), default="")
    contact_city: str = Field(validation_alias=AliasPath("contact", "city"), default="")
    contact_business: str = Field(validation_alias=AliasPath("contact", "business"), default="")
    contact_homepage: str = Field(validation_alias=AliasPath("contact", "homepage"), default="")
    contact_emails: str = Field(validation_alias=AliasPath("contact", "emails"), default="")
    contact_inn: str = Field(validation_alias=AliasPath("contact", "inn"), default="")
    contact_kpp: str = Field(validation_alias=AliasPath("contact", "kpp"), default="")
    contact_created_at: str = Field(validation_alias=AliasPath("contact", "created_at"), default="")
    contact_updated_at: str = Field(validation_alias=AliasPath("contact", "updated_at"), default="")
    contact_deleted_at: str = Field(validation_alias=AliasPath("contact", "deleted_at"), default="")
    contact_parent_lead_id: str = Field(validation_alias=AliasPath("contact", "parent_lead_id"), default="")
    contact_tags: str = Field(validation_alias=AliasPath("contact", "tags"), default="")
    contact_address: str = Field(validation_alias=AliasPath("contact", "address"), default="")
    contact_phones: str = Field(validation_alias=AliasPath("contact", "phones"), default="")

    call_id: int = Field(validation_alias=AliasPath("call", "id"), default="")
    call_phone: str = Field(validation_alias=AliasPath("call", "phone"), default="")
    call_source: str = Field(validation_alias=AliasPath("call", "source"), default="")
    call_direction: str = Field(validation_alias=AliasPath("call", "direction"), default="")
    call_params: dict = Field(validation_alias=AliasPath("call", "params"), default="")
    call_lead_id: int = Field(validation_alias=AliasPath("call", "lead_id"), default="")
    call_organization_id: int = Field(validation_alias=AliasPath("call", "organization_id"), default="")
    call_user_id: int = Field(validation_alias=AliasPath("call", "user_id"), default="")
    call_started_at: str = Field(validation_alias=AliasPath("call", "started_at"), default="")
    call_connected_at: str = Field(validation_alias=AliasPath("call", "connected_at"), default="")
    call_ended_at: str = Field(validation_alias=AliasPath("call", "ended_at"), default="")
    call_reason: str = Field(validation_alias=AliasPath("call", "reason"), default="")
    call_duration: int = Field(validation_alias=AliasPath("call", "duration"), default="")
    call_scenario_id: int = Field(validation_alias=AliasPath("call", "scenario_id"), default="")
    call_result_id: int = Field(validation_alias=AliasPath("call", "result_id"), default="")
    call_incoming_phone: str | None = Field(validation_alias=AliasPath("call", "incoming_phone"), default="")
    call_recording_url: str | None = Field(validation_alias=AliasPath("call", "recording_url"), default="")
    call_call_type: str = Field(validation_alias=AliasPath("call", "call_type"), default="")
    call_region: str = Field(validation_alias=AliasPath("call", "region"), default="")
    call_local_time: str = Field(validation_alias=AliasPath("call", "local_time"), default="")
    call_call_project_id: int = Field(validation_alias=AliasPath("call", "call_project_id"), default="")
    call_call_project_title: str = Field(validation_alias=AliasPath("call", "call_project_title"), default="")
    call_scenario_result_group_id: int = Field(validation_alias=AliasPath("call", "scenario_result_group_id"), default="")
    call_scenario_result_group_title: str = Field(validation_alias=AliasPath("call", "scenario_result_group_title"), default="")

    call_result_result_id: int = Field(validation_alias=AliasPath("call_result", "result_id"), default="")
    call_result_result_name: str = Field(validation_alias=AliasPath("call_result", "result_name"), default="")
    call_result_comment: str | None = Field(validation_alias=AliasPath("call_result", "comment"), default="")
